### ISSUE TITLE
What is a module?

### ISSUE THREAD

**Issue by szepeviktor** [kaisekidev/kaiseki-scaffold-wp-module#1]
Hello @wolfgangschaefer!
What is a "WordPress module"?

**Comment by wolfgangschaefer** [comment]
Hello @szepeviktor!

Sorry for answering so late.

A "WordPress module" is a composer package containing classes and their factories to be used in conjunction with dependency injection.

With https://github.com/kaisekidev/kaiseki-container-builder you can setup dependency injection inside your theme, and use modules to add functionality contained in modules like https://github.com/kaisekidev/kaiseki-wp-hook.

This repository is used to create new modules and is only used via the command `composer create-project kaiseki/scaffold-wp-module [Directory]`.

**Comment by szepeviktor** [comment]
Thank you.

BTW You can prevent two times `kaiseki` in Composer
```json
  "extra": {
    "installer-paths": {
      "public/wp-content/plugins/{$vendor}-{$name}/": [
        "type:wordpress-plugin"
      ]
    }
  },
```
